# Site settings
title: 기억보조용 위키
url: "https://wiki.code-toolbox.com"
baseurl: ""
description: >
    배운것들 적기

# My information
email: moltak@gmail.com
author: kh
github_username: moltak
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
  wiki:
    output: true
    permalink: /:collection/:path/

# Comment Service
disqus:
  id: moltak
  shortname: moltak 
utterances:
  repo: moltak/moltak.github.io
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

github: "https://github.com/moltak/moltak.github.io"
blame: "https://github.com/moltak/moltak.github.io/blame/master/_wiki"
edit: "https://github.com/moltak/moltak.github.io/edit/master/_wiki"
issue: "https://github.com/moltak/moltak.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]

theme: minima

defaults:
  - scope:
      path: "assets/images"
    values: 
      image: true
