# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               엔갱 
tagline:             '개발 흔적 남기기'
description:         '개발하면서 좋았던 해결 방법들이나 새롭게 배운것들 남김.'
url:                 https://moltak.github.io
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              엔갱
  url:               https://moltak.github.io
  email:             moltak@gmail.com

# Custom vars
version:             0.0.1

google_analytics:    ''

plugins:
  - jekyll-paginate